<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> Good example of Async and the best practice of handling error in Async
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:core%40lists.ocaml.org?Subject=Re%3A%20Good%20example%20of%20Async%20and%20the%20best%20practice%20of%20handling%20error%20in%20Async&In-Reply-To=%3CCAEDxudzq1Z_x18%3DpGensOexJdGpEKQdWROpKgSUg47QvESeGtQ%40mail.gmail.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="000361.html">
   <LINK REL="Next"  HREF="000362.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>Good example of Async and the best practice of handling error in Async</H1>
    <B>Yury Sulsky</B> 
    <A HREF="mailto:core%40lists.ocaml.org?Subject=Re%3A%20Good%20example%20of%20Async%20and%20the%20best%20practice%20of%20handling%20error%20in%20Async&In-Reply-To=%3CCAEDxudzq1Z_x18%3DpGensOexJdGpEKQdWROpKgSUg47QvESeGtQ%40mail.gmail.com%3E"
       TITLE="Good example of Async and the best practice of handling error in Async">yury.sulsky at gmail.com
       </A><BR>
    <I>Wed May 23 15:49:00 BST 2012</I>
    <P><UL>
        <LI>Previous message: <A HREF="000361.html">Good example of Async and the best practice of handling error in Async
</A></li>
        <LI>Next message: <A HREF="000362.html">Good example of Async and the best practice of handling error in Async
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#359">[ date ]</a>
              <a href="thread.html#359">[ thread ]</a>
              <a href="subject.html#359">[ subject ]</a>
              <a href="author.html#359">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>
Hi Yoriyuki,

Since Pipe.map doesn't handle exceptions, the situation you describe
won't occur. The exception will stop the iteration of Pipe.map and
bubble up to you. Here's an example program. Note that the exception
bubbles up to whatever monitor was in effect when the call to Pipe.map
took place.

# open Core.Std;;
# open Async.Std;;
# let r, w = Pipe.create ();;
# let rec loop = function
    | 10 -&gt; return ()
    |  x -&gt; Pipe.write w x &gt;&gt;= fun () -&gt; loop (x + 1)
  in whenever (loop 0);;
# let f i = if i &gt; 5 then failwithf &quot;too big: %d&quot; i () else i;;
# Monitor.try_with (fun () -&gt;
    let r' = Pipe.map ~f r in
    Pipe.iter_without_pushback r' ~f:(printf &quot;*** read %d\n&quot;))
  &gt;&gt;| function
    | Ok () -&gt; ()
    | Error exn -&gt; printf &quot;*** caught exn %s\n&quot; (Exn.to_string exn);;
# Scheduler.go ();;
*** read 0
*** read 1
*** read 2
*** read 3
*** read 4
*** read 5
*** caught exn (monitor.ml.Error_
  ((exn (Failure &quot;too big: 6&quot;))
    (backtrace
      (&quot;Raised at file \&quot;pervasives.ml\&quot;, line 22, characters 22-33&quot;
        &quot;Called from file \&quot;core_queue.ml\&quot;, line 60, characters 35-38&quot;
        &quot;Called from file \&quot;queue.ml\&quot;, line 134, characters 6-20&quot;
        &quot;Called from file \&quot;core_queue.ml\&quot;, line 60, characters 2-40&quot;
        &quot;Called from file \&quot;pipe.ml\&quot;, line 584, characters 52-62&quot;
        &quot;Called from file \&quot;scheduler.ml\&quot;, line 65, characters 12-23&quot; &quot;&quot;))
    (monitor
      (((name_opt (try_with)) (id 2) (has_seen_error true)
         (someone_is_listening true))
        ((name_opt (main)) (id 1) (has_seen_error false)
          (someone_is_listening false))))))

On Wed, May 23, 2012 at 9:27 AM, Yoriyuki Yamagata &lt;<A HREF="http://lists.ocaml.org/listinfo/core">yoriyuki.y at gmail.com</A>&gt; wrote:
&gt;<i> Hi, list.
</I>&gt;<i>
</I>&gt;<i> 2012/5/22 Yaron Minsky &lt;<A HREF="http://lists.ocaml.org/listinfo/core">yminsky at janestreet.com</A>&gt;:
</I>&gt;&gt;<i> Maybe you could write a simple code snippet showing a case where
</I>&gt;&gt;<i> you're unsure what the right behavior is? &#160;That might help us focus in
</I>&gt;&gt;<i> on answering the right question.
</I>&gt;<i>
</I>&gt;<i> How about this one?
</I>&gt;<i>
</I>&gt;<i> let f c = if Char.code c &lt; 0x80 then c else raise Out_of_bound in
</I>&gt;<i> reader' = &#160;Pipe.map reader ~f
</I>&gt;<i>
</I>&gt;<i> I think Pipe's reader does not handle the exception, so reader' just
</I>&gt;<i> skips non-Ascii character after raising exception. &#160;Am I correct?
</I>&gt;<i>
</I>&gt;<i> If f is more complex (say, it has internal states), such behavior
</I>&gt;<i> would cause a strange result (all outputs from reader are garbage
</I>&gt;<i> after the exception, for example). &#160; So any alternatives? &#160;Maybe we
</I>&gt;<i> make f return char option, but I feel it too heavy.
</I>&gt;<i>
</I>&gt;<i> Best,
</I>&gt;<i>
</I>&gt;<i> --
</I>&gt;<i> Yoriyuki&#12288;Yamagata
</I>&gt;<i> <A HREF="http://lists.ocaml.org/listinfo/core">yoriyuki.y at gmail.com</A>
</I>
</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="000361.html">Good example of Async and the best practice of handling error in Async
</A></li>
	<LI>Next message: <A HREF="000362.html">Good example of Async and the best practice of handling error in Async
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#359">[ date ]</a>
              <a href="thread.html#359">[ thread ]</a>
              <a href="subject.html#359">[ subject ]</a>
              <a href="author.html#359">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://lists.ocaml.org/listinfo/core">More information about the core
mailing list</a><br>
</body></html>
